HW-2: Calculate prices added
Daniel3579/MTS pull request #1
Opened 2023-12-15 10:11 UTC by Daniel3579

Add 2 classes:

- Product – product fields and  `getPriceList` method

- TestProduct – create 3 objects and launch the program

2023-12-15 16:07 UTC, dvcvms requested changes

2023-12-15 16:07 UTC, dvcvms commented on HW_2/Product.java
> +    float discount; // product discount
При финансовых подсчетах следует использовать класс BigDecimal. Подробнее можно прочитать тут - https://javarush.com/groups/posts/2274-kak-ispoljhzovatjh-bigdecimal-v-java.

Подправь)

2023-12-15 16:07 UTC, dvcvms commented on HW_2/Product.java
> +
Добавь многострочный комментарий с описанием, что делает класс (это по заданию)

2023-12-15 16:07 UTC, dvcvms commented on HW_2/Product.java
> +     * @param discount
Хороший тон, добавлять описание, что означает тот или иной параметр, раз он указан в комментарии:

@param price - количество ... и так везде)

2023-12-15 16:07 UTC, dvcvms commented on HW_2/Product.java
> +     * @param amount
Между конструктором и @param сделай 1 пустую строчку. Это по конвенции комментариев.

2023-12-15 16:07 UTC, dvcvms commented on HW_2/Product.java
> +     */
Тут те же замечания, что и выше)

2023-12-15 16:07 UTC, dvcvms commented on HW_2/Product.java
> +        System.out.printf("Price with discount: %.2f\n", p.amount * p.price * (1 - p.discount));
Вынеси логику подсчета цены в отдельные методы и запихни это в отдельный класс.

2023-12-15 16:07 UTC, dvcvms commented on HW_2/TestProduct.java
> +}
По сути TestProduct  не отражает по своему имени то, что он делает. Предлагаю создать отдельный тестовый класс, где добавить тесты, проверяющие, что подсчет цены со скидкой и без работает верно.

2023-12-15 16:07 UTC, dvcvms commented on HW_2/TestProduct.java
> +    public static void main(String[] args) {
Сделай отступ в 1 строчку)

2023-12-15 16:07 UTC, dvcvms commented on HW_2/TestProduct.java
> +}
Измени название этого класса на то, что по сути он делает)

2023-12-15 16:10 UTC, dvcvms commented
Нужно еще использовать систему сборки приложения. Например gradle или maven. На уроках вам рекомендовали использовать gradle. Сделай это)

2023-12-15 20:42 UTC, Daniel3579 commented on HW_2/Product.java
> +    float discount; // product discount
Изменил на BigDecimal

2023-12-15 20:43 UTC, Daniel3579 commented on HW_2/Product.java
> +
Многострочные комментарии с описанием для всех классов добавил

2023-12-15 20:43 UTC, Daniel3579 commented on HW_2/Product.java
> +     * @param discount
Каждый параметр подписал

2023-12-15 20:44 UTC, Daniel3579 commented on HW_2/Product.java
> +     * @param amount
Отступ сделал

2023-12-15 20:44 UTC, Daniel3579 commented on HW_2/Product.java
> +     */
Отступ сделал, параметр подписал

2023-12-15 20:45 UTC, Daniel3579 commented on HW_2/Product.java
> +        System.out.printf("Price with discount: %.2f\n", p.amount * p.price * (1 - p.discount));
Вынес в новый класс `PriceListMethods` и создал 2 новых метода:

- `getPriceWithDiscount`
- `getPriceWithoutDiscount`

2023-12-15 20:46 UTC, Daniel3579 commented on HW_2/TestProduct.java
> +}
Переименовал класс в `TestProductPriceListCorrectness`

2023-12-15 20:46 UTC, Daniel3579 commented on HW_2/TestProduct.java
> +    public static void main(String[] args) {
Отступ сделал

2023-12-15 20:48 UTC, Daniel3579 commented
Gradle файлы добавил)

2023-12-17 21:10 UTC, dvcvms commented on src/main/java/HW_2/Product.java
> +    BigDecimal discount; // product discount
Почитай про один из принципов ООП - инкапсуляцию. Тут нужно было добавить private, геттеры и сеттеры.

2023-12-17 21:10 UTC, dvcvms commented on HW_2/Product.java
> +    float discount; // product discount
Принято

2023-12-17 21:12 UTC, dvcvms commented on src/main/java/HW_2/Product.java
> +     * @param discount set product discount
Тут нужно было описать, что каждый из параметр означает)

например:

price - цена продукта
discount - скидка

2023-12-17 21:15 UTC, dvcvms commented on src/main/java/HW_2/Product.java
> +        this.discount = discount;
Здесь можно было добавить проверку, что

amount >= 0
price >= 0
0 <= discount <= 100

это по условию)


Имей это в виду в будущем при работе с кодом

2023-12-17 21:16 UTC, dvcvms commented on src/main/java/HW_2/TestProductPriceListCorrectness.java
> +    }
Прочитай, как писать простые unit тесты. Достаточно использовать Junit - покроет все хотелки на текущем уровне)

2023-12-17 21:16 UTC, dvcvms commented on HW_2/Product.java
> +
Принято

2023-12-17 21:17 UTC, dvcvms commented on HW_2/Product.java
> +     * @param discount
Принято

2023-12-17 21:17 UTC, dvcvms commented on HW_2/Product.java
> +     * @param amount
Принято

2023-12-17 21:17 UTC, dvcvms commented on HW_2/Product.java
> +     */
Принято

2023-12-17 21:18 UTC, dvcvms commented on HW_2/Product.java
> +        System.out.printf("Price with discount: %.2f\n", p.amount * p.price * (1 - p.discount));
Принято

2023-12-17 21:18 UTC, dvcvms commented on HW_2/TestProduct.java
> +}
Принято.

2023-12-17 21:18 UTC, dvcvms commented on HW_2/TestProduct.java
> +    public static void main(String[] args) {
Принято.

2023-12-17 21:19 UTC, dvcvms commented
Можно мерджить)

2023-12-18 21:46 UTC, merged

2023-12-18 21:46 UTC, Daniel3579 commented
Add 3 classes:

* Product – product fields
* PriceListMethods – 2 methods `getPriceWithDiscount` and `getPriceWithoutDiscount`
* TestProductPriceListCorrectness – create 3 objects and launch the program